export const REMINDER_TIMEZONES = [
  { value: "Africa/Lagos", label: "West Africa Time (Africa/Lagos)" },
  { value: "Africa/Accra", label: "Ghana Time (Africa/Accra)" },
  { value: "Africa/Johannesburg", label: "South Africa Time (Africa/Johannesburg)" },
  { value: "UTC", label: "UTC" },
  { value: "Europe/London", label: "United Kingdom (Europe/London)" },
  { value: "Europe/Paris", label: "Central Europe (Europe/Paris)" },
  { value: "America/New_York", label: "US Eastern (America/New_York)" },
  { value: "America/Chicago", label: "US Central (America/Chicago)" },
  { value: "America/Denver", label: "US Mountain (America/Denver)" },
  { value: "America/Phoenix", label: "Arizona (America/Phoenix)" },
  { value: "America/Los_Angeles", label: "US Pacific (America/Los_Angeles)" },
  { value: "America/Toronto", label: "Canada Eastern (America/Toronto)" },
  { value: "America/Vancouver", label: "Canada Pacific (America/Vancouver)" },
  { value: "America/Sao_Paulo", label: "Brazil (America/Sao_Paulo)" },
  { value: "Asia/Dubai", label: "UAE (Asia/Dubai)" },
  { value: "Asia/Kolkata", label: "India (Asia/Kolkata)" },
  { value: "Asia/Singapore", label: "Singapore (Asia/Singapore)" },
  { value: "Asia/Tokyo", label: "Japan (Asia/Tokyo)" },
  { value: "Australia/Perth", label: "Australia West (Australia/Perth)" },
  { value: "Australia/Sydney", label: "Australia East (Australia/Sydney)" },
];
